/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package servlet_demo;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.Charset;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebInitParam;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@WebServlet(
		name="FIRST_SERVLET",
		value ="/",
		initParams = {
			@WebInitParam(name="matricola", value = "123456"),
			@WebInitParam(name="professione", value="tornitore")
		}
	)
public class FirstServlet extends HttpServlet{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Override
	public void init(ServletConfig config) throws ServletException {
		
		super.init(config);
		System.out.println("first servlet initialized");
		System.out.println("name="+config.getServletName());
		System.out.println("matricola="+config.getInitParameter("matricola"));
		System.out.println("professione="+config.getInitParameter("professione"));
		
		ServletContext ctx=getServletContext();
		System.out.println("context path="+ctx.getContextPath());
		System.out.println("major version="+ctx.getEffectiveMajorVersion());
		System.out.println("minor version="+ctx.getEffectiveMinorVersion());
		System.out.println("server info="+ctx.getServerInfo());
		System.out.println("session timeout="+ctx.getSessionTimeout());
		
		System.out.println("PARAM1="+ctx.getInitParameter("PARAM1"));
		System.out.println("PARAM2="+ctx.getInitParameter("PARAM2"));
		System.out.println("ATTR1="+ctx.getAttribute("ATTR1"));
		System.out.println("ATTR2="+ctx.getAttribute("ATTR2"));
		
	}

	@Override
	protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		
		System.out.println(req.toString());
		System.out.println(resp.toString());
		
		ServletContext ctx = this.getServletContext();
		ctx.setAttribute("NEW_PAR", "new_val_1");
		ctx.setAttribute("NEW_PAR", "new_val_2");
		ctx.setAttribute("NEW_PAR", null);
		
		String message = "<h1>Hello World!!!</h1>";
		OutputStream outStream = resp.getOutputStream();
		outStream.write(message.getBytes(Charset.forName("UTF-8")));
		outStream.flush();
	}
	
	/**
	 * chiamato solo in 
	 * undeploy del pacchetto
	 */

	@Override
	public void destroy() {
		super.destroy();
		System.out.println("deep servlet destroyed");
	}
	
    
}
