/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package servlet_demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        FirstServlet classUnderTest = new FirstServlet();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
